export interface PRDescriptionOptions {
  operation: string;
  source: string;
  appliedFindings: Array<{
    title: string;
    severity?: string;
    files: string[];
    category?: string;
  }>;
  skippedFindings: Array<{ title: string; severity?: string }>;
  failedFindings: Array<{ title: string; severity?: string; error: string }>;
}

const severityEmoji: Record<string, string> = {
  critical: "\u{1F534}",
  high: "\u{1F7E0}",
  medium: "\u{1F7E1}",
  low: "\u{1F535}",
  info: "\u26AA",
};

export function buildPRTitle(operation: string, count: number): string {
  return `fix: apply ${count} Shipwell ${operation} finding${count !== 1 ? "s" : ""}`;
}

export function buildPRDescription(opts: PRDescriptionOptions): string {
  const { operation, source, appliedFindings, skippedFindings, failedFindings } =
    opts;
  const lines: string[] = [];

  // Header
  lines.push(`## \u{1F6E0}\uFE0F Shipwell Auto-Fix: ${operation}`);
  lines.push("");
  lines.push(
    `Automated fixes generated by [Shipwell](https://shipwell.app/) analysis.`,
  );
  lines.push("");

  // Applied fixes table
  if (appliedFindings.length > 0) {
    lines.push(`### \u2705 Applied Fixes (${appliedFindings.length})`);
    lines.push("");
    lines.push("| Severity | Finding | Files |");
    lines.push("|----------|---------|-------|");
    for (const f of appliedFindings) {
      const emoji = severityEmoji[f.severity ?? "info"] ?? "\u26AA";
      const files = f.files.slice(0, 3).map((p) => `\`${p}\``).join(", ");
      const extra = f.files.length > 3 ? ` +${f.files.length - 3} more` : "";
      lines.push(`| ${emoji} ${f.severity ?? "info"} | ${f.title} | ${files}${extra} |`);
    }
    lines.push("");

    // Collapsible details
    lines.push("<details>");
    lines.push("<summary>Finding details</summary>");
    lines.push("");
    for (const f of appliedFindings) {
      const emoji = severityEmoji[f.severity ?? "info"] ?? "\u26AA";
      lines.push(`#### ${emoji} ${f.title}`);
      if (f.category) {
        lines.push(`**Category:** ${f.category}`);
      }
      lines.push(
        `**Files:** ${f.files.map((p) => `\`${p}\``).join(", ")}`,
      );
      lines.push("");
    }
    lines.push("</details>");
    lines.push("");
  }

  // Skipped findings
  if (skippedFindings.length > 0) {
    lines.push(`### \u23ED\uFE0F Skipped (${skippedFindings.length}) — no diff available`);
    lines.push("");
    for (const f of skippedFindings) {
      const emoji = severityEmoji[f.severity ?? "info"] ?? "\u26AA";
      lines.push(`- ${emoji} ${f.title}`);
    }
    lines.push("");
  }

  // Failed findings
  if (failedFindings.length > 0) {
    lines.push(`### \u274C Failed (${failedFindings.length})`);
    lines.push("");
    for (const f of failedFindings) {
      const emoji = severityEmoji[f.severity ?? "info"] ?? "\u26AA";
      lines.push(`- ${emoji} ${f.title} — _${f.error}_`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(
    "_Generated by [Shipwell](https://shipwell.app/) \u{1F6A2}_",
  );

  return lines.join("\n");
}
